<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="CHNMCT279709L" failures="1" tests="1" name="Default test" time="0.075" errors="0" timestamp="2020-12-15T16:12:13 IST">
  <testcase classname="Api.DevQAApplication" name="deleteTest" time="0.03">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Api.DevQAApplication.deleteTest(int)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: deleteTest([Parameter{index=0, type=int, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 38.0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Api.DevQAApplication.deleteTest(int)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: deleteTest([Parameter{index=0, type=int, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 38.0]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:905)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- deleteTest -->
  <testcase classname="Api.DevQAApplication" name="test_validation" time="0.0">
    <ignored/>
  </testcase> <!-- test_validation -->
  <testcase classname="Api.DevQAApplication" name="test_001_emp_greater_4lakhs" time="0.0">
    <ignored/>
  </testcase> <!-- test_001_emp_greater_4lakhs -->
  <testcase classname="Api.DevQAApplication" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="Api.DevQAApplication" name="postTestData" time="0.0">
    <ignored/>
  </testcase> <!-- postTestData -->
  <testcase classname="Api.DevQAApplication" name="excelPostTest" time="0.0">
    <ignored/>
  </testcase> <!-- excelPostTest -->
  <testcase classname="Api.DevQAApplication" name="failed_validation" time="0.0">
    <ignored/>
  </testcase> <!-- failed_validation -->
  <testcase classname="Api.DevQAApplication" name="test_002_emp_greater_2lakhs" time="0.0">
    <ignored/>
  </testcase> <!-- test_002_emp_greater_2lakhs -->
  <testcase classname="Api.DevQAApplication" name="test_002_emp_greater_3lakhs" time="0.0">
    <ignored/>
  </testcase> <!-- test_002_emp_greater_3lakhs -->
</testsuite> <!-- Default test -->
